### ISSUE TITLE
Document manual installation

### ISSUE THREAD

**Issue by mguillem** [revelc/formatter-m2e-configurator#36]
According to the currently opened issues, automatic discovery is not trivial to implement. In the mean time, a short explaination about how to perform manual installation would be really helpful. Manually installing the configurator plugin in Eclipse is not enough to get the it working.

**Comment by hazendaz** [comment]
Will update readme after next release but this works as-is form many years by simply adding this to your sites in eclipses.

https://search.maven.org/remotecontent?filepath=net/revelc/code/formatter/net.revelc.code.formatter.site/2.5.0/net.revelc.code.formatter.site-2.5.0.zip

I think for ease of usage, I'll get 2.6.0 released next weekend using same methodology then will update the docs since that method seems to work without manually doing this.  Of course more testing and will look to see how to get over to m2e so its listed there automatically as presumably it can use the same link.

**Comment by hazendaz** [comment]
ok that process is a bit different, cannot load it from central directly, it must be downloaded.  Closing as updating readme now.
